### PR TITLE
[FeatureRequest: Issue #329] Adding ARM64 Support 

### PR DESCRIPTION
**Pull request by Sreeratm**
## What problem does this Pull Request solve?
- Adding ARM64 support for Terraform-provider-openapi. Based on the ticket SLTF-5 and Issue #329 .
Please link to the issue number here (issue will be closed when PR is merged): Closes # 329
                                                              

## Type of change

What type of change does your code introduce to the provider? Please put an `x` (w/o heading/trailing white spaces) in the boxes that apply:

- [x ] New feature (change that adds new functionality)
- [ ] Bug-fix (change that fixes current functionality)
- [ ] Tech debt (enhances the current functionality)
- [ ] New release (pumps the version)

## Checklist

Please put an `x` (w/o heading/trailing white spaces) in the boxes that apply:

- [ x] I have read and followed the [CONTRIBUTING](https://github.com/dikhan/terraform-provider-api/blob/master/.github/CONTRIBUTING.md) guidelines
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have made sure code compiles correctly and all tests are passing by running `make test-all`
- [ ] I have added/updated necessary documentation (if appropriate)
- [x ] I have added the following info to the title of the PR (pick the appropriate option for the type of change). This is important because the release notes will include this information.
  - [x] Feature Request: PRs related to feature requests should have in the title `[FeatureRequest: Issue #X] <PR Title>`
  - [ ] Bug Fixes: PRs related to bug fixes should have in the title `[BugFix: Issue #X] <PR Title>`
  - [ ] Tech Debt: PRs related to technical debt should have in the title `[TechDebt: Issue #X] <PR Title>` 
  - [ ] New Release: PRs related to a new release should have in the title `[NewRelease] vX.Y.Z`

## Checklist for Admins
- [x] Label is populated
- [x] PR is assigned to the corresponding project
- [x] PR has at least 1 reviewer and 1 assignee

### CODE REVIEW

**Comment by dikhan** [comment]
Looks like the build notification was not sent properly to travis ci and the build has not started. Gonna attempt to force push a build by closing the PR and reopening it again and hopefully that will unblock the PR build. 

Additionally, I will open a ticket with travis ci to get more info about why this happened.

**Comment by dikhan** [comment]
Looks like the closing and immediate reopening of the PR did the trick, waiting for the build to finish, generally the changes look good.

**Review by dikhan — APPROVED** [review]
Thanks for contributing @Sreeratm , the PR looks good. Merging it now.

**Comment by Sreeratm** [comment]
Thanks @dikhan

**Pull request merged**
