### PR TITLE
[FeatureRequest: Issue #305] Support colon characters in field names

### LINKED ISSUE #305: InternalValidate Error on "-" character in swagger.json
## Describe the bug
`terraform validate` fails when the terraform-provider-openapi binary walks [my service provider's](https://docs.antsle.com/system/using-the-antman-rest-api-with-terraform) swagger.json file. It asks me to file a bug report: "Internal validation of the provider failed! This is always a bug with the provider itself, and not a user issue. Please report this bug"

## To Reproduce
I'm attempting to use [Terraform 1.0.0](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability) and this [project's 2.0.6 release](https://github.com/dikhan/terraform-provider-openapi/releases/tag/v2.0.6) together with my service provider's API. I'm attempting to use[ local provider mirroring](https://www.terraform.io/docs/cli/config/config-file.html#explicit-installation-method-configuration) so that I can have multiple terraform projects pull the terraform-provider-openapi from my local disk at `terraform init` time.

1. Create a terraform project directory: `mkdir test`
2. Put `provider.tf` and `main.tf` in this directory
Contents of provider.tf:
```
terraform {
  required_providers {
    antsle = {
      source = "localhost/antsle/antsle"
      version = "~> 1.0.0"
    }
  }
}

variable "apikey_auth" {
  default = "Token ey"
}

provider "antsle" {
  api_key = var.apikey_auth
}

```
Contents of main.tf:
```
resource "antsle_antlets" "antlet1" {
  dname       = "antlet"
  template    = "debian"
  ram         = 1024
  cpu         = 1
  antlet_num  = 33
  zpool_name  = "antlets"
  compression = "lz4"
}
```
3. Put the following in your ~/.terraformrc file, replacing my name with your home directory name:
```
provider_installation {
   filesystem_mirror {
     path    = "/home/brad/.local/share/terraform/plugins/"
     include = ["localhost/*/*"]
   }
}
```
4. Put the 2.0.6 release binary renamed to `terraform-provider-antsle` and the `terraform-provider-openapi.yaml` files into `~/.local/share/terraform/plugins/localhost/antsle/antsle/1.0.0/linux_amd64/`
Contents of `~/.local/share/terraform/plugins/localhost/antsle/antsle/1.0.0/linux_amd64/terraform-provider-openapi.yaml`:
```
version: 1
services:
    antsle:
      swagger-url: https://cscijoy.antsle.us/swagger.json
```
5. Back in your `test` directory, run `terraform init`. This succeeds; the .terraformrc and provider.tf work together to symlink the project directory's `.terraform/providers/localhost/antsle/antsle/1.0.0/linux_amd64` to `~/.local/share/terraform/plugins/localhost/antsle/antsle/1.0.0/linux_amd64`.
6. Finally, run `terraform validate` or `terraform plan`. The error occurs here.

## Expected behaviour
`terraform validate` does not crash.

## Additional context
I ran `export TF_LOG=TRACE` before running `terraform validate` to [generate some logs](https://gist.github.com/bradthebuilder/f3c3ccfdc6f7b037d63bd30c0c622f90). The error message is all the way down at the bottom. My take-away from scrutinizing this is that the four main terraform-compatible APIs that are mapped to Antsle resources are successfully found and registered with the provider binary, but the `managed-origin` string in the `swagger.json` causes the openapi provider binary to hiccup. It looks like it tries to convert the dash character into an underscore in the output, but something maybe just goes wrong in that process.

Without access to an Antsle device (and it's swagger.json), I don't expect this to be easy to re-create for anyone on the team, but I'm more than willing to run tests and collaborate if this is believed to be a bug with this provider. If I'm mistaken and this is a lack of robustness of the service provider's API (I.E. their problem), please feel free to close this issue. The URL for the swagger.json is for my Antsle device on my local network, and I don't think the software's terms of service/EULA will allow me to share all of it. Screenshots provided along with [logs gist](https://gist.github.com/bradthebuilder/f3c3ccfdc6f7b037d63bd30c0c622f90) to help make sense of the problem.

Bug
antsle_managed-origin

### PR DESCRIPTION
**Pull request by bradthebuilder**
## What problem does this Pull Request solve?

Please link to the issue number here (issue will be closed when PR is merged): Closes #305 
                                                              
## Type of change

What type of change does your code introduce to the provider? Please put an x (w/o heading/trailing white spaces) in the boxes that apply:

- [x] New feature (change that adds new functionality)
- [ ] Bug-fix (change that fixes current functionality)
- [ ] Tech debt (enhances the current functionality)
- [ ] New release (pumps the version)

## Checklist

Please put an `x` (w/o heading/trailing white spaces) in the boxes that apply:

- [x] I have read and followed the [CONTRIBUTING](https://github.com/dikhan/terraform-provider-api/blob/master/.github/CONTRIBUTING.md) guidelines
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have made sure code compiles correctly and all tests are passing by running `make test-all`
- [ ] I have added/updated necessary documentation (if appropriate)
- [x] I have added the following info to the title of the PR (pick the appropriate option for the type of change). This is important because the release notes will include this information.
  - [x] Feature Request: PRs related to feature requests should have in the title `[FeatureRequest: Issue #X] <PR Title>`
  - [ ] Bug Fixes: PRs related to bug fixes should have in the title `[BugFix: Issue #X] <PR Title>`
  - [ ] Tech Debt: PRs related to technical debt should have in the title `[TechDebt: Issue #X] <PR Title>` 
  - [ ] New Release: PRs related to a new release should have in the title `[NewRelease] vX.Y.Z`

## Checklist for Admins
- [x] Label is populated
- [x] PR is assigned to the corresponding project
- [x] PR has at least 1 reviewer and 1 assignee

## Commentary
All unit tests pass on my system.

The following integration tests in  `tests/integration/resource_monitors_test.go` failed on my laptop _before_ and after my changes were added:
- TestAccMonitor_CreateRst1
- TestAccMonitor_CreateDub1
- TestAccMonitor_MultiRegion_CreateRst1
- TestAccMonitor_MultiRegion_CreateDub1
- TestAccMonitor_MultiRegion_Create_Default_Region

[Integration test error stdout](https://gist.github.com/bradthebuilder/94e5c1b4749a4f48d96b6d7adce14328)

I figured it had something to do with my local network's DNS not being configured to resolve the API URLs used in the tests (I guess the docker containers bridged to my laptop), so I figured Travis CI would be the gatekeeper in this discrepancy. The errors were present on the master branch before my additions and are still there afterward, so I'm confident my additions at least didn't make things worse. If this is an actual bug and not an issue with my environment, I can work on a separate bug-hunting branch.

The provider _does_ compile and I tested it against the docker-compose local-env and my Antsle device. It works on my Antsle device perfectly, and 3/4 resources get created with the swaggercodegen example on `terraform apply` (`terraform validate` and `terraform plan` work fine).

swaggercodegen_firewall_failure

I think it's because the resource name has more than one number character in it; I noticed when adding my unit tests that the `ConvertToTerraformCompliantName` function cannot handle more than one distinct number in a field name. Once again, I can work on this in a separate bug branch if we're in agreement.

### CODE REVIEW

**Comment by dikhan** [comment]
Hi @bradthebuilder , thanks for opening the PR! I just had a baby so most likely won't have time to look into this for a little while. I am expecting to come back to work in couple weeks. I will review the PR and provide feedback then. Sorry for the delay!

**Comment by dikhan** [comment]
Hey @bradthebuilder ,

Thanks for contributing! The PR looks good, I went ahead and merged the new commits from master to bring this PR up to date. I see the CI build job is failing and I am guessing it's due to the build job being triggered from a fork and the docker login complaining about not being able to perform an interactive login. I was trying to push a new commit against your upstream `master` and even the `feature/support-colon-chars` but I am getting permissions denied. Usually I am able to contribute back to PRs created by contributors by pushing new commits against their upstream branches but it's not this time for some reason, not sure what I am missing. Any thoughts?

Alternatively I can create a new PR against a new branch I pushed which contains the latest from master, your commits and the new commit that I wanted to add, you can check out the branch here: https://github.com/dikhan/terraform-provider-openapi/commits/bradthebuilder-master

Let me know

**Comment by bradthebuilder** [comment]
Howdy @dikhan ,

I admit, I'm a bit rusty with GitHub permissions because I do most of my work on Gitlab, but I just tried inviting you as a Collaborator to my fork; maybe accepting that invitation will allow you to push against my `master` branch? If that didn't do the trick, I'll consult GitHub's documentation on Friday to see if it's something obvious I missed. Failing that, we can fall back to your suggestion of a new branch for plan B.

I did make make another commit on my feature/terraform-gte-1.0.0 branch that adjusts `/scripts/install.sh` to accept Terraform versions greater than or equal to 1.0.0 that we can also look at a PR for once we get this first one ironed out. Thanks for allowing me to contribute!

**Comment by dikhan** [comment]
Hey @bradthebuilder ,

I managed to push to your fork in the end but unfortunately was not able to fix the issue with the builds not working in forks.  Looks like in [Travis CI encrypted environment variables are not available to pull requests from forks](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) due to the security risk of exposing such information to unknown code, and hence commands like docker login used to be able to run the integration tests in the pipeline fail to execute from forks. 

Considering the build was failing due to reasons not related to this PR and also having confirmed that all the tests passed locally I feel confortable merging the PR even if the build is red. Once the PR is merged, all the tests will kick off again and this time they will execute properly since the build would be triggered from this repo itself. For the record I am attaching the output of the tests results run locally:

[PR306_test_results_run_locally.txt](https://github.com/dikhan/terraform-provider-openapi/files/6860104/PR306_test_results_run_locally.txt)

Lastly, @bradthebuilder I just wanted to let you know that the [Publishing OpenAPI Terraform providers in the Terraform Registry](https://github.com/dikhan/terraform-provider-openapi/blob/master/docs/publishing_provider.md) doc has instructions on how to leverage the OpenAPI Terraform repo as a library and be able to publish your own Terraform provider (powered by the OpenAPI Terraform provider) in the Terraform registry in case you are interested.

With that, thanks again for contributing to the repo!

Dani

**Review by dikhan — APPROVED** [review]

**Pull request merged**
